name: Browser (small test)

on:
  workflow_call:
    inputs:
      browser-name:
        type: string
        required: true
      playwright-version:
        type: string
        required: true

env:
  NODE_VERSION: 20.x

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 依存関係をインストール
        run: |
          npm ci
          npm i -D playwright@${{ inputs.playwright-version }}
          npx playwright install --with-deps ${{ inputs.browser-name }}

      - name: テスト
        run: npx vitest tests/small/
        env:
          VITEST_MODE: ${{ inputs.browser-name }}
