name: Browser (medium test)

on:
  workflow_call:
    inputs:
      browser-name:
        type: string
        required: true
      playwright-version:
        type: string
        required: true
      surrealdb-version:
        type: string
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: 依存関係をインストール
        run: |
          npm ci
          npm i -D playwright@${{ inputs.playwright-version }}
          npx playwright install --with-deps ${{ inputs.browser-name }}
          bash scripts/pretest/setup_surrealdb.sh ${{ inputs.surrealdb-version }}

      - name: テスト
        run: |
          touch /tmp/logs
          bun run scripts/pretest/serve.js &>>/tmp/logs &

          npx vitest tests/medium/
        env:
          VITEST_MODE: ${{ inputs.browser-name }}

      - name: SurrealDB のログ
        run: cat /tmp/logs
        if: always()
