name: Bun

on: push

jobs:
  small:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        bun-version:
          - "1.1.13"
          - "latest"
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: 依存関係をインストール
        run: bun install

      - name: テスト
        run: VITEST_MODE='bun' bunx vitest tests/small/

  medium:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        bun-version:
          - "1.1.13"
          - "latest"
        surrealdb-version:
          - "alpha"
          # - "v2.0.0"
          # - "latest"
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: 依存関係をインストール
        run: |
          bun install
          bash scripts/pretest/setup_surrealdb.sh ${{ matrix.surrealdb-version }}

      - name: テスト
        run:  |
          touch /tmp/logs
          bun run scripts/pretest/serve.js &>>/tmp/logs &

          bunx vitest tests/medium/
        env:
          VITEST_MODE: bun

      - name: SurrealDB のログ
        run: cat /tmp/logs
        if: always()
