name: Canary Release on NPM

on:
  push:
    branches:
      - v1
    paths:
      - ".github/workflows/canary-release.yml"
      - "scripts/**"
      - "src/**"
      - "package-lock.json"
      - "package.json"
      - "tsconfig.json"

jobs:
  next:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - run: npm ci

      - run: npm run build

      - name: Pin version
        run: |
          npm --no-git-tag-version version minor
          npm --no-git-tag-version version "$(npm pkg get version | jq -r)-next.$(date --utc +'%Y%m%dT%H%M%S')"

      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          tag: next
