name: Canary Release on NPM

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/canary-release.yml"
      - "scripts/**"
      - "src/**"
      - "package-lock.json"
      - "package.json"
      - "tsconfig.build.json"
      - "tsconfig.json"

env:
  NODE_VERSION: 20.x
  SURREALDB_VERSION: beta
  BUMP_PACKAGE_VERSION: major # major, minor
  PRERELEASE_PACKAGE_TAG: next

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 依存関係をインストール
        run: |
          npm ci
          bash scripts/pretest/setup_surrealdb.sh ${{ env.SURREALDB_VERSION }}

      - name: テスト
        run: |
          touch /tmp/logs
          bun run scripts/pretest/serve.js &>>/tmp/logs &

          npx vitest tests/
        env:
          VITEST_MODE: node.js

      - name: SurrealDB のログ
        run: cat /tmp/logs
        if: always()

  next:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v4

      - name: Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 依存関係をインストール
        run: npm ci

      - name: ビルド
        run: npm run build

      - name: バージョン設定
        run: |
          npm --no-git-tag-version version ${{ env.BUMP_PACKAGE_VERSION }}
          npm --no-git-tag-version version "$(npm pkg get version | jq -r)-next.$(date --utc +'%Y%m%dT%H%M%S')"

      - name: 公開
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          tag: ${{ env.PRERELEASE_PACKAGE_TAG }}
