name: Chromium

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/chromium.yml"
      - "src/**"
      - "tests/**"
      - "scripts/**"
      - "*.json"
      - "*.ts"
  pull_request:
    paths-ignore:
      - "docs/**"

jobs:
  small:
    name: small (playwright@${{ matrix.playwright-version }})
    uses: ./.github/workflows/browser.small.yml
    with:
      browser-name: chromium
      playwright-version: ${{ matrix.playwright-version }}
    strategy:
      matrix:
        playwright-version:
          # よくわからないが 1.22 以前では依存関係のインストールに失敗する。
          - "1.23" # Chromium 104
          - "latest"
      fail-fast: false

  medium:
    name: medium (playwright@${{ matrix.playwright-version }}, surrealdb@${{ matrix.surrealdb-version }})
    uses: ./.github/workflows/browser.medium.yml
    with:
      browser-name: chromium
      playwright-version: ${{ matrix.playwright-version }}
      surrealdb-version: ${{ matrix.surrealdb-version }}
    strategy:
      matrix:
        playwright-version:
          # よくわからないが 1.22 以前では依存関係のインストールに失敗する。
          - "1.23" # Chromium 104
          - "latest"
        surrealdb-version:
          - "beta"
          # - "v2.0.0"
          # - "latest"
      fail-fast: false
