name: Chromium

on:
  push:
    branches:
      - v1

jobs:
  small:
    uses: ./.github/workflows/browser.small.yml
    with:
      browser-name: chromium
      playwright-version: ${{ matrix.playwright-version }}
    strategy:
      matrix:
        playwright-version:
          # よくわからないが 1.22 以前では依存関係のインストールに失敗する。
          - "1.23" # Chromium 104
          - "latest"
      fail-fast: false

  medium:
    uses: ./.github/workflows/browser.medium.yml
    with:
      browser-name: chromium
      playwright-version: ${{ matrix.playwright-version }}
      surrealdb-version: ${{ matrix.surrealdb-version }}
    strategy:
      matrix:
        playwright-version:
          # よくわからないが 1.22 以前では依存関係のインストールに失敗する。
          - "1.23" # Chromium 104
          - "latest"
        surrealdb-version:
          - "v1.5.0"
          - "v1.5.4"
      fail-fast: false
