name: Codecov

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/codecov.yml"
      - "src/**"
      - "tests/**"
      - "*.json"
      - "*.ts"

jobs:
  coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        surrealdb-version:
          - "alpha"
          # - "v2.0.0"
          # - "latest"
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: 依存関係をインストール
        run: |
          npm ci
          bash scripts/pretest/setup_surrealdb.sh ${{ matrix.surrealdb-version }}

      - name: カバレッジ
        run: |
          touch /tmp/logs
          bun run scripts/pretest/serve.js &>>/tmp/logs &

          npx vitest tests/ --run --coverage
        env:
          VITEST_MODE: node.js

      - uses: codecov/codecov-action@v4
        with:
          files: ./coverage/coverage-final.json
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: SurrealDB のログ
        run: cat /tmp/logs
        if: always()
