name: Codecov

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/codecov.yml"
      - "src/**"
      - "tests/**"
      - "*.json"
      - "*.ts"

env:
  NODE_VERSION: 20.x
  SURREALDB_VERSION: beta
  PLAYWRIGHT_VERSION: latest

jobs:
  coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 依存関係をインストール
        run: |
          npm ci
          npm i -D playwright@${{ env.PLAYWRIGHT_VERSION }}
          npx playwright install --with-deps chromium
          bash scripts/pretest/setup_surrealdb.sh ${{ env.SURREALDB_VERSION }}

      - name: カバレッジ
        run: |
          touch /tmp/logs
          bun run scripts/pretest/serve.js &>>/tmp/logs &

          VITEST_MODE='node.js'  npx vitest tests/ --coverage
          VITEST_MODE='chromium' npx vitest tests/ --coverage

      - uses: codecov/codecov-action@v4
        with:
          files: ./coverage/node.js/coverage-final.json,./coverage/chromium/coverage-final.json
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

      - name: SurrealDB のログ
        run: cat /tmp/logs
        if: always()
