name: Deno

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deno.yml"
      - ".github/workflows/nightly.yml"
      - "src/**"
      - "tests/**"
      - "scripts/**"
      - "*.json"
      - "*.ts"
  pull_request:
    paths:
      - ".github/workflows/deno.yml"
      - ".github/workflows/nightly.yml"
      - "src/**"
      - "tests/**"
      - "scripts/**"
      - "*.json"
      - "*.ts"
  workflow_dispatch:

jobs:
  small:
    name: small (deno@${{ matrix.deno-version }})
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        deno-version:
          - "1.x"
          - "2.x"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Deno ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: "依存関係をインストール"
        run: npm ci

      - name: "テスト"
        run: deno -A npm:vitest tests/small/
        env:
          VITEST_MODE: deno

  medium:
    name: medium (deno@${{ matrix.deno-version }}, surrealdb@${{ matrix.surrealdb-version }})
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        deno-version:
          - "1.x"
          - "2.x"
        surrealdb-version:
          - "v2.1.0"
          - "latest"
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Deno ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: "依存関係をインストール"
        run: |
          npm ci
          bash scripts/pretest/setup_surrealdb.sh ${{ matrix.surrealdb-version }}

      - name: "テスト"
        run: |
          touch /tmp/logs
          bun run scripts/pretest/serve.js &>>/tmp/logs &

          deno -A npm:vitest tests/medium/
        env:
          VITEST_MODE: deno

      - name: "SurrealDB のログ"
        run: cat /tmp/logs
        if: always()
