name: Firefox

on: push

jobs:
  small:
    uses: ./.github/workflows/browser.small.yml
    with:
      browser-name: firefox
      playwright-version: ${{ matrix.playwright-version }}
    strategy:
      matrix:
        playwright-version:
          # よくわからないが 1.22 以前では依存関係のインストールに失敗する。
          - "1.23" # Firefox 100
          - "latest"
      fail-fast: false

  # small:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 30
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       playwright-version:
  #         - "1.23" # Firefox 100
  #         - "latest"
  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: "20.x"

  #     - name: Setup
  #       run: |
  #         npm ci
  #         npm i -D playwright@${{ matrix.playwright-version }}
  #         npx playwright install --with-deps firefox

  #     - name: Test
  #       run: VITEST_MODE='Firefox' npx vitest tests/small/
