name: Firefox

on: push

jobs:
  small:
    uses: ./.github/workflows/browser.small.yml
    with:
      browser-name: firefox
      playwright-version: ${{ matrix.playwright-version }}
    strategy:
      matrix:
        playwright-version:
          # よくわからないが 1.22 以前では依存関係のインストールに失敗する。
          - "1.23" # Firefox 100
          - "latest"
      fail-fast: false
