name: GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/gh-pages.yml"
      - "docs/**"
  workflow_dispatch:

env:
  NODE_VERSION: 20.x

jobs:
  build:
    defaults:
      run:
        working-directory: docs
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: "依存関係をインストール"
        run: npm i

      - name: "ビルド"
        run: npm run build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
