name: Nightly tests

on:
  schedule:
    - cron: "0 9 * * *"

jobs:
  nodejs:
    name: Server (node@${{ matrix.nodejs-version }}, surrealdb@${{ matrix.surrealdb-version }})
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        nodejs-version:
          - "22.x"
        surrealdb-version:
          - "nightly"
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Node.js ${{ matrix.nodejs-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodejs-version }}

      - name: "依存関係をインストール"
        run: |
          npm ci
          bash scripts/pretest/setup_surrealdb.sh ${{ matrix.surrealdb-version }}

      - name: "テスト"
        run: |
          touch /tmp/logs
          bun run scripts/pretest/serve.js &>>/tmp/logs &

          npx vitest tests/
        env:
          VITEST_MODE: node.js

      - name: "SurrealDB のログ"
        run: cat /tmp/logs
        if: always()

  chromium:
    name: Browser (playwright@${{ matrix.playwright-version }}, surrealdb@${{ matrix.surrealdb-version }})
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        playwright-version:
          - "latest"
        surrealdb-version:
          - "nightly"
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: "依存関係をインストール"
        run: |
          npm ci
          npm i -D playwright@${{ matrix.playwright-version }}
          npx playwright install --with-deps chromium
          bash scripts/pretest/setup_surrealdb.sh ${{ matrix.surrealdb-version }}

      - name: "テスト"
        run: |
          touch /tmp/logs
          bun run scripts/pretest/serve.js &>>/tmp/logs &

          npx vitest tests/
        env:
          VITEST_MODE: chromium

      - name: "SurrealDB のログ"
        run: cat /tmp/logs
        if: always()
