name: Node.js

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/nodejs.yml"
      - "src/**"
      - "tests/**"
      - "scripts/**"
      - "*.json"
      - "*.ts"
  pull_request:
    paths-ignore:
      - "docs/**"

jobs:
  static:
    name: static (node@${{ matrix.nodejs-version }})
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        nodejs-version:
          - "20.x"
    steps:
      - uses: actions/checkout@v4

      - name: Node.js ${{ matrix.nodejs-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodejs-version }}

      - name: "依存関係をインストール"
        run: npm ci

      - name: "型確認"
        run: npx tsc --noEmit
        if: always()

      - name: "体裁確認"
        run: npx dprint check
        if: always()

      - name: "サイズ確認"
        run: npm run test:size
        if: always()

  small:
    name: small (node@${{ matrix.nodejs-version }})
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        nodejs-version:
          - "18.x"
          - "20.x"
          - "22.x"
    steps:
      - uses: actions/checkout@v4

      - name: Node.js ${{ matrix.nodejs-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodejs-version }}

      - name: "依存関係をインストール"
        run: npm ci

      - name: "テスト"
        run: npx vitest tests/small/
        env:
          VITEST_MODE: node.js

  medium:
    name: medium (node@${{ matrix.nodejs-version }}, surrealdb@${{ matrix.surrealdb-version }})
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        nodejs-version:
          # TODO(tai-kun): v18 だけなんか失敗する。要調査。
          # - "18.x"
          - "20.x"
          - "^22.5.1"
        surrealdb-version:
          - "beta"
          # - "v2.0.0"
          # - "latest"
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Node.js ${{ matrix.nodejs-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodejs-version }}

      - name: "依存関係をインストール"
        run: |
          npm ci
          bash scripts/pretest/setup_surrealdb.sh ${{ matrix.surrealdb-version }}

      - name: "テスト"
        run: |
          touch /tmp/logs
          bun run scripts/pretest/serve.js &>>/tmp/logs &

          npx vitest tests/medium/
        env:
          VITEST_MODE: node.js

      - name: "SurrealDB のログ"
        run: cat /tmp/logs
        if: always()

  examples:
    name: examples (node@${{ matrix.nodejs-version }}, surrealdb@${{ matrix.surrealdb-version }})
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        nodejs-version:
          # TODO(tai-kun): v18 だけなんか失敗する。要調査。
          # - "18.x"
          - "20.x"
        surrealdb-version:
          - "beta"
          # - "v2.0.0"
          # - "latest"
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Node.js ${{ matrix.nodejs-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodejs-version }}

      - name: "依存関係をインストール"
        run: |
          npm ci
          bash scripts/pretest/setup_surrealdb.sh ${{ matrix.surrealdb-version }}

      - name: "テスト"
        run: |
          touch /tmp/logs
          bun run scripts/pretest/serve.js &>>/tmp/logs &

          npx vitest tests/examples/
        env:
          VITEST_MODE: node.js

      - name: "SurrealDB のログ"
        run: cat /tmp/logs
        if: always()
