name: Node.js

on:
  push:
    branches:
      - v1

jobs:
  small:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        nodejs-version:
          - "18.x"
          - "20.x"
          - "22.x"
    steps:
      - uses: actions/checkout@v4

      - name: Node.js ${{ matrix.nodejs-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodejs-version }}

      - name: 依存関係をインストール
        run: npm ci

      - name: テスト
        run: VITEST_MODE='node.js' npx vitest tests/small/

  medium:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        nodejs-version:
          # TODO(tai-kun): v18 だけなんか失敗する。要調査。
          # - "18.x"
          - "20.x"
          - "^22.5.1"
        surrealdb-version:
          - "alpha"
          # - "v2.0.0"
          # - "latest"
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Node.js ${{ matrix.nodejs-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodejs-version }}

      - name: 依存関係をインストール
        run: |
          npm ci
          bash scripts/pretest/setup_surrealdb.sh ${{ matrix.surrealdb-version }}

      - name: テスト
        run: |
          touch /tmp/logs
          bun run scripts/pretest/serve.js &>>/tmp/logs &

          npx vitest --run tests/medium/
        env:
          VITEST_MODE: node.js

      - name: SurrealDB のログ
        run: cat /tmp/logs
        if: always()

  examples:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        nodejs-version:
          # TODO(tai-kun): v18 だけなんか失敗する。要調査。
          # - "18.x"
          - "20.x"
          - "^22.5.1"
        surrealdb-version:
          - "alpha"
          # - "v2.0.0"
          # - "latest"
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Node.js ${{ matrix.nodejs-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodejs-version }}

      - name: 依存関係をインストール
        run: |
          npm ci
          bash scripts/pretest/setup_surrealdb.sh ${{ matrix.surrealdb-version }}

      - name: テスト
        run: |
          touch /tmp/logs
          bun run scripts/pretest/serve.js &>>/tmp/logs &

          npx vitest --run tests/medium/
        env:
          VITEST_MODE: node.js

      - name: SurrealDB のログ
        run: cat /tmp/logs
        if: always()
