name: Pull Request

on:
  pull_request:

jobs:
  check-title:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: "チェック"
        run: node --run commit-msg
        env:
          COMMIT_MESSAGE: ${{ github.event.pull_request.title }}
