name: WebKit

on:
  push:
    branches:
      - main

jobs:
  small:
    uses: ./.github/workflows/browser.small.yml
    with:
      browser-name: webkit
      playwright-version: ${{ matrix.playwright-version }}
    strategy:
      matrix:
        playwright-version:
          # よくわからないが 1.22 以前では依存関係のインストールに失敗する。
          - "1.23" # WebKit 15.4
          - "latest"
      fail-fast: false

  # TODO(tai-kun): CORS を無効化する方法を探す。
  # medium:
  #   uses: ./.github/workflows/browser.medium.yml
  #   with:
  #     browser-name: webkit
  #     playwright-version: ${{ matrix.playwright-version }}
  #     surrealdb-version: ${{ matrix.surrealdb-version }}
  #   strategy:
  #     matrix:
  #       playwright-version:
  #         # よくわからないが 1.22 以前では依存関係のインストールに失敗する。
  #         - "1.23" # WebKit 15.4
  #         - "latest"
  #       surrealdb-version:
  #         - "alpha"
  #         # - "v2.0.0"
  #         # - "latest"
  #     fail-fast: false
